### ISSUE TITLE
The upgrade recipe from Bartalli Sailboat to Epheria Frigate is no longer accurate

### ISSUE THREAD

**Issue by gcallant** [xanthics/bdo_ship_upgrade#2]
As of April 1, 2021, According to the in-game upgrade UI, the recipe for upgrade should be:

Bartali Sailboat Old Prow +10 : Correct
Bartali Sailboat Old Plating +10 : Correct
Bartali Sailboat Old Cannon +10 : Correct
Bartali Sailboat Old Sail +10 : Correct

Standardized Timber Square 1000 : Correct
Jade Coral Ingot 800 : Incorrect (Currently shows 600)
Pine coated Plywood 1000 : Incorrect (Currently shows 1500)
Enhanced Flax Fabric 450 : Incorrect (Currently shows 300)
Hard Pillar 100: Correct

Ship Upgrade Permit: Epheria Frigate (200M): Incorrect (Currently shows None)

The recipe for upgrade from Bartali to Epheria Sailboat is still correct. 

Let me know if you have any questions- thank you for your work- I really appreciate the utility.

**Comment by xanthics** [comment]
Can you attach an image of the in game ui?  (windows+shift+s to snip if you are on win10)

**Comment by gcallant** [comment]
#3 
![image](https://user-images.githubusercontent.com/11579798/113359956-ace4f780-92fd-11eb-9cec-d149f36fa03b.png)

**Comment by xanthics** [comment]
I've merged your https://github.com/xanthics/bdo_ship_upgrade/pull/3 pull request to resolve this issue.  Thank you.

I'm curious when it was changed as even [grumpygreen](https://grumpygreen.cricket/bdo-bartali-sailboat-upgrade-guide-how-to-recipe-materials/) has the wrong values

**Comment by gcallant** [comment]
No problem, thank you for the quick reply. I'm curious myself, as I had just discovered the discrepancy myself when going to upgrade.
