### ISSUE TITLE
Wrong Material Counts

### ISSUE THREAD

**Issue by MohammadAdiyudha** [xanthics/bdo_ship_upgrade#5]
Hello, thanks for making this web, it really helps my progress to do ship upgrading

I noticed the material count for Tide-Dyed Standardized Timber Square is wrong, it should be 3, not 6.

![image](https://github.com/xanthics/bdo_ship_upgrade/assets/54175795/7bcec0a4-9e74-4788-bc22-c68d128b01f3)

![2024-06-18_08-12-32](https://github.com/xanthics/bdo_ship_upgrade/assets/54175795/f74fecf3-58e0-4d37-be9d-51f9080af0f9)

**Comment by xanthics** [comment]
Should be good to go.  Thank you for the report.
