### ISSUE TITLE
Need Update to Latest Info

### ISSUE THREAD

**Issue by MohammadAdiyudha** [xanthics/bdo_ship_upgrade#6]
Thanks for making this web, i found it really helpful to track ship progress, but if possible, can you update to the latest information?

there are some things that need updated, example :
- daily / weekly reward count (PA merge some daily quest & make the rewards better)
- no use of fiery & frosted black stone (PA deleted it)
- etc

**Comment by xanthics** [comment]
https://github.com/xanthics/bdo_ship_upgrade/commit/a4bd0850c5d0c4c63b360463c365f2c9348a3999

Let me know if that didn't address everything.

**Comment by MohammadAdiyudha** [comment]
thanks for updating the black stone, i'll provide the link about quest that i mentioned, there's change of sailing quest daily / weekly rewards & merged quest, please check it out

https://blackdesert.pearlabyss.com/ASIA/en-us/News/Notice/Detail?_boardNo=6061

**Comment by MohammadAdiyudha** [comment]
> [a4bd085](https://github.com/xanthics/bdo_ship_upgrade/commit/a4bd0850c5d0c4c63b360463c365f2c9348a3999)
> 
> Let me know if that didn't address everything.

thanks for updating the black stone, i'll provide the link about quest that i mentioned, there's change of sailing quest daily / weekly rewards & merged quest, please check it out

https://blackdesert.pearlabyss.com/ASIA/en-us/News/Notice/Detail?_boardNo=6061

**Comment by xanthics** [comment]
> little bit out of topic, i think now is perfect time to playing back bdo because PA gave us free PEN BS today haha

I already had PEN weapons ;o  Burned myself out with those failure rates.

**Comment by MohammadAdiyudha** [comment]
poor, i also never get pen bs myself with enchant haha

this is sailing quest & reward summary from sailing discord, i hope it's help your development
https://imgur.com/a/YuHkjvF

**Comment by MohammadAdiyudha** [comment]
thanks, really appreciate that
