### ISSUE TITLE
Update to Recent Patch (August 8, 2024)

### ISSUE THREAD

**Issue by MohammadAdiyudha** [xanthics/bdo_ship_upgrade#8]
Hello

According to recent update, the materials for upgrading Bartali Sailboat to Epheria Sailboat & Epheria Frigate become lesser
https://www.naeu.playblackdesert.com/en-US/News/Detail?groupContentNo=7391&countryType=en-US

thanks

**Comment by xanthics** [comment]
![image](https://github.com/user-attachments/assets/1ecbf96d-d335-4fa2-979e-f5bb1ed3fd92)
This doesn't mention Hard Pillars, but I have that as part of the recipe currently.  Is it still part of the recipe and they forgot it, or was it removed?

**Comment by MohammadAdiyudha** [comment]
i think hard pillar is part of **improved** epheria sailboat & epheria frigate materials, not for regular sailboat & frigate

**Comment by MohammadAdiyudha** [comment]
the recent patch only for regular sailboat & frigate

**Comment by xanthics** [comment]
from looking through bdocodex, it looks like a few recipes have changed.  I'll do a once over pass "soonish" (within a week) and make sure they are all updated.  EG sailboats require gold bars now

**Comment by MohammadAdiyudha** [comment]
thank you verey much, dont forget the LOML ship (panokseon) too haha
